TRUNCATE "WADE"."CATALOG_SUMMARY_MV_merge";

SELECT * FROM  "WADE"."CATALOG_SUMMARY_MV_ATOC";

INSERT INTO "WADE"."CATALOG_SUMMARY_MV_merge" ("ORGANIZATION_ID", "WADE_URL", "REPORT_ID", "DATACATEGORY", "DATATYPE", "STATE", "REPORT_UNIT_ID", "REPORTING_UNIT_NAME", "COUNTY_FIPS", "HUC")
SELECT "ORGANIZATION_ID", "WADE_URL", "REPORT_ID", "DATACATEGORY", "DATATYPE", "STATE", "REPORT_UNIT_ID", "REPORTING_UNIT_NAME", "COUNTY_FIPS", "HUC" FROM "WADE"."CATALOG_SUMMARY_MV_ATOC";

SELECT * FROM  "WADE"."CATALOG_SUMMARY_MV_DTON";

INSERT INTO "WADE"."CATALOG_SUMMARY_MV_merge" ("ORGANIZATION_ID", "WADE_URL", "REPORT_ID", "DATACATEGORY", "DATATYPE", "STATE", "REPORT_UNIT_ID", "REPORTING_UNIT_NAME", "COUNTY_FIPS", "HUC")
SELECT "ORGANIZATION_ID", "WADE_URL", "REPORT_ID", "DATACATEGORY", "DATATYPE", "STATE", "REPORT_UNIT_ID", "REPORTING_UNIT_NAME", "COUNTY_FIPS", "HUC" FROM "WADE"."CATALOG_SUMMARY_MV_DTON";

SELECT * FROM  "WADE"."CATALOG_SUMMARY_MV_OTOS";

INSERT INTO "WADE"."CATALOG_SUMMARY_MV_merge" ("ORGANIZATION_ID", "WADE_URL", "REPORT_ID", "DATACATEGORY", "DATATYPE", "STATE", "REPORT_UNIT_ID", "REPORTING_UNIT_NAME", "COUNTY_FIPS", "HUC")
SELECT "ORGANIZATION_ID", "WADE_URL", "REPORT_ID", "DATACATEGORY", "DATATYPE", "STATE", "REPORT_UNIT_ID", "REPORTING_UNIT_NAME", "COUNTY_FIPS", "HUC" FROM "WADE"."CATALOG_SUMMARY_MV_OTOS";

SELECT * FROM  "WADE"."CATALOG_SUMMARY_MV_TTOZ";

INSERT INTO "WADE"."CATALOG_SUMMARY_MV_merge" ("ORGANIZATION_ID", "WADE_URL", "REPORT_ID", "DATACATEGORY", "DATATYPE", "STATE", "REPORT_UNIT_ID", "REPORTING_UNIT_NAME", "COUNTY_FIPS", "HUC")
SELECT "ORGANIZATION_ID", "WADE_URL", "REPORT_ID", "DATACATEGORY", "DATATYPE", "STATE", "REPORT_UNIT_ID", "REPORTING_UNIT_NAME", "COUNTY_FIPS", "HUC" FROM "WADE"."CATALOG_SUMMARY_MV_TTOZ";

--INSERT INTO "WADE"."CATALOG_SUMMARY_MV_merge" (

SELECT * FROM  "WADE"."CATALOG_SUMMARY_MV_merge";