TRUNCATE "WADE"."CATALOG_SUMMARY_MV";

SELECT * FROM  "WADE"."CATALOG_SUMMARY_MV_merge";

INSERT INTO "WADE"."CATALOG_SUMMARY_MV" ("ORGANIZATION_ID", "WADE_URL", "REPORT_ID", "DATACATEGORY", "DATATYPE", "STATE", "REPORT_UNIT_ID", "REPORTING_UNIT_NAME", "COUNTY_FIPS", "HUC")
SELECT "ORGANIZATION_ID", "WADE_URL", "REPORT_ID", "DATACATEGORY", "DATATYPE", "STATE", "REPORT_UNIT_ID", "REPORTING_UNIT_NAME", "COUNTY_FIPS", "HUC" FROM "WADE"."CATALOG_SUMMARY_MV_merge";

SELECT * FROM  "WADE"."CATALOG_SUMMARY_MV";